/** Disciplinas “Outras” (concursos / Gran) — valor guardado em `question.subject` ao filtrar. */
export const OUTRAS_DISCIPLINES: readonly string[] = [
  'Administração de Recursos Materiais',
  'Administração Financeira e Orçamentária - AFO',
  'Administração Geral',
  'Administração Pública',
  'Agricultura e Agropecuária',
  'Análise das Demonstrações Contábeis',
  'Antropologia',
  'Arqueologia',
  'Arquitetura',
  'Arquivologia',
  'Artes',
  'Atendimento ao Público',
  'Atualidades e Conhecimentos Gerais',
  'Atuária',
  'Auditoria',
  'Biblioteconomia',
  'Biologia',
  'Ciência Política',
  'Ciências Aeronáuticas',
  'Comércio Internacional',
  'Comunicação Social',
  'Conhecimentos Bancários',
  'Conhecimentos Específicos de um determinado Cargo/Área',
  'Contabilidade de Custos',
  'Contabilidade Geral',
  'Contabilidade Pública',
  'Controle da Administração',
  'Criminalística',
  'Criminologia',
  'Desenho Industrial',
  'Direito Administrativo',
  'Direito Agrário',
  'Direito ambiental',
  'Direito Civil',
  'Direito Constitucional',
  'Direito do Consumidor (Lei 8.078/1990)',
  'Direito do Trabalho',
  'Direito Eleitoral',
  'Direito Empresarial (Comercial)',
  'Direito Financeiro',
  'Direito Internacional',
  'Direito Notarial e Registral',
  'Direito Penal',
  'Direito Penal Militar',
  'Direito Previdenciário',
  'Direito Processual Civil - CPC 1973',
  'Direito Processual Civil - CPC 2015',
  'Direito Processual do Trabalho',
  'Direito Processual Penal',
  'Direito Processual Penal Militar',
  'Direito Sanitário e Saúde',
  'Direito Tributário',
  'Direito Urbanístico',
  'Direitos Difusos, Coletivos e Individuais Homogêneos',
  'Direitos Humanos',
  'Economia e Finanças',
  'Educação Física',
  'Enfermagem',
  'Engenharia Agronômica',
  'Engenharia Ambiental e Sanitária',
  'Engenharia Aquacultura/Aquicultura',
  'Engenharia Cartográfica e de Agrimensura',
  'Engenharia Civil',
  'Engenharia Clínica',
  'Engenharia de Alimentos',
  'Engenharia de Avaliações',
  'Engenharia de Materiais',
  'Engenharia de Minas',
  'Engenharia de Pesca',
  'Engenharia de Petróleo e Gás',
  'Engenharia de Produção',
  'Engenharia de Qualidade',
  'Engenharia de Recursos Hídricos/Hidráulica',
  'Engenharia de Telecomunicações',
  'Engenharia de Transportes e Trânsito',
  'Engenharia Elétrica e Engenharia Eletrônica',
  'Engenharia Espacial',
  'Engenharia Física',
  'Engenharia Florestal',
  'Engenharia Genética',
  'Engenharia Industrial',
  'Engenharia Mecânica',
  'Engenharia Mecatrônica',
  'Engenharia Metalúrgica',
  'Engenharia Naval',
  'Engenharia Nuclear',
  'Engenharia Portuária',
  'Engenharia Química',
  'Estatística',
  'Estilismo/Design de Moda',
  'Ética',
  'Farmácia',
  'Filosofia',
  'Filosofia do Direito',
  'Finanças Públicas',
  'Física',
  'Fisioterapia',
  'Fonoaudiologia',
  'Gastronomia',
  'Geografia',
  'Geologia',
  'Gestão Jurídica',
  'História',
  'Informática',
  'Inteligência Policial',
  'Legislação de Trânsito e CTB',
  'Legislação dos Órgãos',
  'Legislação Estadual, Distrital e Municipal',
  'Legislação Federal',
  'Lei Complementar nº 101/2000 e alterações (Lei de Responsabilidade Fiscal - LRF)',
  'Lei Complementar nº 840/2011',
  'Lei nº 10.741/2003 - Estatuto do Idoso',
  'Lei nº 11.340/2006 - Lei Maria da Penha',
  'Lei nº 13.146/2015 - Estatuto da Pessoa com Deficiência',
  'Lei nº 7.210/1984 - Lei de Execução Penal - LEP',
  'Lei nº 8.069/1990 - Estatuto da Criança e do Adolescente / ECA',
  'Lei Orgânica do Distrito Federal - LODF',
  'Língua Espanhola',
  'Língua Francesa',
  'Língua Inglesa',
  'Língua Portuguesa',
  'Línguas (Outras)',
  'Matemática',
  'Matemática Financeira',
  'Medicina',
  'Medicina Legal',
  'Meio Ambiente',
  'Meteorologia',
  'Metodologia Científica',
  'Museologia',
  'Nutrição',
  'Oceanografia',
  'Odontologia',
  'Pedagogia',
  'Política Internacional',
  'Primeiros Socorros',
  'Psicologia',
  'Química',
  'Raciocínio Lógico',
  'Redação Oficial',
  'Regimento Interno',
  'Relações Humanas',
  'Relações Internacionais',
  'Relações Públicas',
  'Secretariado',
  'Segurança e Saúde no Trabalho (Teoria e Normas)',
  'Serviço Social',
  'Sistemas de Informação',
  'Sociologia (Ciências Sociais)',
  'Tecnologia da Informação',
  'Teologia e Religiões',
  'Terapia Ocupacional',
  'Turismo e Hotelaria',
  'Veterinária',
  'Zootecnia',
];
