/** Disciplinas oficiais SanFran (nome + código) — pesquisa por texto ou código. */
export const SANFRAN_DISCIPLINES: readonly string[] = [
  'A Estrutura da Governança Corporativa - DCO0428',
  'A Moeda entre a Sociologia Jurídica e a Sociologia Econômica: Teoria, Política e Instituições numa Economia Globalizada - DFD0320',
  'Acesso à Justiça - DPC0217',
  'Ações Autônomas de impugnação no processo penal - DPC0538',
  'Administração Indireta - DES0339 / DES0342',
  'Agentes Públicos - DES0532',
  'Análise de Jurisprudência Constitucional - DES0336',
  'Análise econômica dos métodos de solução de conflitos - DPC0449',
  'Antropologia Jurídica - DFD0326',
  'Aplicação da Concorrência e Mercado - DCO0323',
  'Arbitragem e Processo - DPC0442',
  'Bases Normativas da Administração Pública - DES0341 / DES0346',
  'Bens Públicos - DES0337 / DES0344',
  'Biodireito - DPM0524',
  'Brazilian Constitutional Law in Comparative Perspective - DES0229',
  'Capitalismo e Direito do Trabalho - DTB0450',
  'Centralidade do Trabalho e Leitura Crítica dos Direitos Sociais e Individuais I - DTB0425',
  'Centralidade do Trabalho e Leitura dos Direitos Sociais e Individuais II - DTB0448',
  'Ciências Comportamentais e Direito Elementos Fundamentais e Aplicações Práticas - DEF0460',
  'Cinema e Direito do Trabalho - DTB0429',
  'Comércio Eletrônico - DCO0325',
  'Concorrência e Mercado - DCO0321',
  'Contratos Administrativos - DES0439',
  'Contratos Empresariais - DCO0320',
  'Contratos Especiais - DCV0315',
  'Controle de Constitucionalidade - DES0436',
  'Controle sobre a Administração Pública - DES0426 / DES0451',
  'Controles das Finanças Públicas e do Orçamento - DEF0456',
  'Cooperação jurídica internacional em matéria penal - DPC0536',
  'Criminalística - DPM0522',
  'Criminologia Clínica - DPM0321',
  'Criminologia Crítica I - DPM0217',
  'Criminologia Crítica II - DPM0218',
  'Criminologia Crítica, Subjetividade e Erro Judiciário - DPM0219',
  'Criminologia do Consenso - DPM0116',
  'Crítica Criminológica ao Direito Penal - DPM0220',
  'Desenho Institucional e Separação de Poderes - DES0334',
  'Difusão de Cultura Jurídica I - 0200124',
  'Direito Administrativo - DES0226',
  'Direito Administrativo das Agências de Regulação - DES0533',
  'Direito Administrativo Francês - DES0429',
  'Direito Administrativo Interdisciplinar I - DES0537',
  'Direito Administrativo Interdisciplinar II - DES0538',
  'Direito Agrário - DCV0519',
  'Direito Agroambiental - DCV0518',
  'Direito Ambiental - DEF0430',
  'Direito Ambiental Aplicado - DEF0336',
  'Direito Ambiental I - DEF0315',
  'Direito Ambiental II - DEF0322',
  'Direito Civil e Novas Tecnologias. Direitos da Personalidade. Proteção de Dados Pessoais. Inteligência Artificial - DCV0526',
  'Direito Civil Francês - DCV0413',
  'Direito Coletivo do Trabalho I: Liberdade Sindical - DTB0533',
  'Direito Coletivo do Trabalho II: Formas de Solução de Conflitos Coletivos - DTB0534',
  'Direito Comparado - DIN0443',
  'Direito Comparado II: Perspectiva Asiática com Ênfase no Direito Japonês - DIN0522',
  'Direito Constitucional Estadual - DES0525',
  'Direito Constitucional I: Direitos Fundamentais - DES0223',
  'Direito Constitucional II: Organização do Estado - DES0224',
  'Direito da Criança e do Adolescente - 0200112',
  'Direito da Dívida Pública - DEF0448',
  'Direito da Empresa em Crise - DCO0505',
  'Direito da Inovação Tecnológica - DEF0545',
  'Direito da Saúde - DFD0138',
  'Direito da União Europeia - DIN0316',
  'Direito das Coisas - DCV0314',
  'Direito das Relações Internacionais - DIN0447',
  'Direito de Autor na Sociedade da Comunicação - DCV0522',
  'Direito de Família e Sucessões - DCV0415',
  'Direito Desportivo - DEF0436',
  'Direito Digital - DCV0233',
  'Direito do Comércio Internacional - DIN0441',
  'Direito do Consumidor - DCO0326',
  'Direito do Trabalho à Luz da Teoria Marxista - DTB0213',
  'Direito do Trabalho e Reprodução Social - DTB0343',
  'Direito do Trabalho e Sociedade - DTB0528',
  'Direito do Trabalho I - DTB0327',
  'Direito do Trabalho II - DTB0328',
  'Direito do Trabalho na Perspectiva dos Direitos Sociais - DTB0530',
  'Direito do Trabalho sob Perspectiva de Gênero, Raça e Classe - DTB0433',
  'Direito dos Animais - DPM0424',
  'Direito dos Contratos Internacionais - DIN0518',
  'Direito dos Seguros Privados e Gestão Atuarial - DCO0415',
  'Direito dos Transportes - DCV0419',
  'Direito e Centralidade do Trabalho à Luz das Manifestações Artísticas I - DTB0454',
  'Direito e Centralidade do Trabalho à Luz das Manifestações Artísticas II - DTB0539',
  'Direito e Desenvolvimento Econômico Democrático - DEF0217',
  'Direito e Discriminação - 0200125',
  'Direito e Equidade de Gênero - 0200120',
  'Direito e Justiça - DFD0324',
  'Direito e Legislação Ambiental - DEF0323',
  'Direito e Políticas Públicas I - DES0419',
  'Direito e Políticas Públicas II - DES0444',
  'Direito e Tecnologia: Privacidade e Proteção de Dados - DFD0218',
  'Direito Econômico - DEF0320',
  'Direito Econômico Aplicado - DEF0532',
  'Direito Econômico da Concorrência - DEF0440',
  'Direito Econômico da Infraestrutura - DEF0435',
  'Direito Econômico Digital - DEF0439',
  'Direito Econômico do Subdesenvolvimento - DEF0534',
  'Direito Econômico Internacional - DEF0535',
  'Direito Econômico Privado - DEF0437',
  'Direito Eleitoral I - DES0343',
  'Direito Empresarial da Inovação - DCO0426',
  'Direito Empresarial Global - DCO0503',
  'Direito Empresarial Público - DCO0504',
  'Direito Empresarial Público da Inovação e Acesso ao Conhecimento - DCO0424',
  'Direito Financeiro - DEF0215',
  'Direito Financeiro Aplicado - DEF0528',
  'Direito Financeiro e Políticas Públicas - DEF0450',
  'Direito Financeiro, Sustentabilidade e Meio Ambiente - DEF0549',
  'Direito Individual do Trabalho I - DTB0537',
  'Direito Individual do Trabalho II - DTB0538',
  'Direito Internacional da Propriedade Intelectual - DIN0451',
  'Direito Internacional do Meio Ambiente - DIN0543',
  'Direito Internacional do Trabalho - DIN0524',
  'Direito Internacional dos Direitos Humanos - DIN0527',
  'Direito Internacional Penal e Justiça de Transição - DIN0444',
  'Direito Internacional Privado - DIN0318',
  'Direito Internacional Privado: Aspectos Patrimoniais - DIN0449',
  'Direito Internacional Privado: Aspectos Pessoais - DIN0537',
  'Direito Internacional Privado: Aspectos Processuais - DIN0539',
  'Direito Internacional Público - DIN0315',
  'Direito Marítimo - DIN0544',
  'Direito Municipal - DES0420',
  'Direito Penal e Gênero - DPM0426',
  'Direito Penal e Religião - DPM0523',
  'Direito Penal Econômico - DPM0526',
  'Direito Penal I (Parte Especial) - DPM0319',
  'Direito Penal II (Parte Especial) - DPM0324',
  'Direito Penal III (Parte Especial) - DPM0421',
  'Direito Penal Internacional e Direito Internacional Penal - DIN0525',
  'Direito Processual Civil I Procedimento Comum I - DPC0216',
  'Direito Processual Civil II: Procedimento Comum II - DPC0319',
  'Direito Processual Civil III: Teoria Geral dos Recursos e da Execução - DPC0322',
  'Direito Processual do Trabalho: Execução Trabalhista - DTB0532',
  'Direito Processual do Trabalho: Procedimentos Especiais Trabalhistas - DTB0531',
  'Direito Processual do Trabalho: Processo de Conhecimento Trabalhista - DTB0438',
  'Direito Processual do Trabalho: Recursos Trabalhistas - DTB0529',
  'Direito Processual do Trabalho: Teoria Geral do Processo do Trabalho - DTB0427',
  'Direito Processual Penal I - DPC0320',
  'Direito Processual Penal II - DPC0429',
  'Direito Processual Penal III: Meios de Prova e Meios de Obtenção da Prova - DPC0440',
  'Direito Processual Penal IV - Procedimentos Especiais - DPC0527',
  'Direito Processual Penal Medidas Cautelares Reais - DPC0445',
  'Direito Processual Penal V: Teoria e Prática dos Recursos Penais - DPC0529',
  'Direito Processual Penal VI: Processo Penal e o Direito Internacional dos Direitos Humanos - DPC0534',
  'Direito Processual Tributário - DEF0464 / DEF0546',
  'Direito Público Econômico - 0200111',
  'Direito Romano Atual I - DCV0127',
  'Direito Romano Atual II - DCV0132',
  'Direito Societário I - DCO0413',
  'Direito Societário II - DCO0420',
  'Direito Tributário Constitucional - DEF0452',
  'Direito Tributário I - DEF0429',
  'Direito Tributário II - DEF0434',
  'Direito Tributário Internacional - DEF0547',
  'Direito Tutelar do Trabalho - DTB0541',
  'Direito Urbanístico - DEF0324',
  'Disciplina do Sistema Bancário - DCO0416',
  'Disciplina Jurídica da Moeda, do Crédito e do Câmbio - DEF0539',
  'Disciplina Jurídica do Mercado - DCO0223',
  'Dispute Settlement - DIN0442',
  'Do Estado de Direito ao Estado Democrático de Direito - DES0328',
  'Economia Política - DEF0113',
  'Economia Política II - DEF0114',
  'Emergência Climática, Direitos Humanos e Direitos Animais: Reflexões Jusfilosóficas - DFD0219',
  'Empresa e Direitos Humanos - DCO0224',
  'Epistemologia dos Direitos Sociais - DTB0335',
  'Estado Brasileiro: Diversidade, Preconceito e Discriminação - DES0234',
  'Ética Profissional - DFD0418',
  'Execução Penal e Direitos Humanos - 0200123',
  'Execuções em Espécie - DPC0436',
  'Federalismo Fiscal - DEF0328',
  'Filosofia do Direito I (Parte Geral) - DFD0313',
  'Filosofia do Direito II (Parte Especial) - DFD0322',
  'Filosofia Política e Direito Penal - DPM0527',
  'Fontes das Obrigações: Responsabilidade Civil, Atos Unilaterais e Outras Fontes - DCV0313',
  'Fundamentos de Direito Público - DES0128',
  'Fundamentos de Economia para o Direito - EAE0644',
  'Fundamentos de Microeconomia - DCO0225',
  'Fundamentos e Princípios do Direito Empresarial - DCO0221',
  'Fundamentos Jurídicos do Mercado de Capitais - DCO0506',
  'Fundamentos do Processo Penal - DPC0321',
  'Globalization and International Law - DIN0538',
  'Globalidade e Direito Internacional - DIN0526',
  'Governança Corporativa - DCO0418',
  'Grandes Princípios do Direito Empresarial - 0200109',
  'História das Ideias Políticas no Brasil - DFD0416',
  'História do Direito do Trabalho no Brasil - DTB0101',
  'História do Direito I - DCV0128',
  'História do Direito II - DCV0219',
  'História do Direito Penal - DPM0221',
  'História do Processo Civil Romano - DCV0317',
  'História e Teoria do Estado de Direito - DES0228',
  'Ideologia e Direitos Sociais - DTB0330',
  'Instituições Judiciárias - DPC0439',
  'Instrumentos de Direito Privado na Proteção ao Meio Ambiente - DCV0417',
  'Inteligência Artificial e a Jurisprudência do Futuro - DFD0328',
  'Inteligência Artificial e Processo Penal: Possibilidades e Limites - DPC0533',
  'International Economic Law - DIN0545',
  'International Relations of Law - DIN0445',
  'Interpretação e Fontes do Direito Financeiro - DEF0216',
  'Intervenção Estatal da Propriedade - DES0449',
  'Intervenção Estatal na Propriedade - DES0424',
  'Introdução à Arbitragem: Prática e Simulações - DPC0220',
  'Introdução à Pesquisa Empírica em Métodos de Solução de Conflitos I - DPC0114',
  'Introdução à Pesquisa Empírica em Métodos de Solução de Conflitos II - DPC0221',
  'Introdução à Prática Forense do Direito Privado - 0200121',
  'Introdução à Sociologia P/ Faculdade de Direito - FSL0117',
  'Introdução à vida universitária - 0200122',
  'Introdução ao Direito Ambiental - DEF0219',
  'Introdução ao Direito Contratual do Reino Unido e Estados Unidos da América - DCV0218',
  'Introdução ao Direito Notarial e Registral - DCV0432',
  'Introdução ao Estudo do Digesto - DCV0231',
  'Introdução ao Estudo do Direito I - DFD0117',
  'Introdução ao Estudo do Direito II - DFD0118',
  'Introdução ao Estudo dos Meios de Solução de Controvérsias - DPC0112',
  'Introdução ao Latim Jurídico I - DCV0130',
  'Introdução ao Latim Jurídico II - DCV0217',
  'Introdução ao Pensamento Jurídico-Penal - DPM0114',
  'Introdução ao Pós-Estruturalismo e Crítica ao Poder: entre Deleuze e Foucault - DFD0422',
  'Introdução Geral ao Direito Francês - DFD0315',
  'Introdução Histórica à Moderna Teoria do Direito - DFD0126',
  'Investigação Criminal - DPC0325',
  'Juiz das Garantias no Processo Penal - 0200126',
  'Justiça Penal Negociada - DPC0324',
  'Legal Theory - DFD0136',
  'Legislação Penal Especial - DPM0420',
  'Leituras Avançadas de Filosofia e Teoria do Direito I - DFD0319',
  'Leituras de Direito Constitucional I - DES0327',
  'Leituras de Direito Constitucional II - DES0332',
  'Leituras de Direito Constitucional III - DES0433',
  'Leituras de Direito Constitucional IV - DES0440',
  'Leituras de Direito Constitucional V - DES0529',
  'Leituras de Direito Constitucional VI - DES0534',
  'Leituras de Direito Econômico e Economia Política - DEF0454',
  'Leituras de Teoria Constitucional e da Justiça - DES0531',
  'Ler o Capital à Luz da Forma Jurídica (Livro I) - Parte 2 - DTB0342',
  'Ler O Capital à Luz da Forma Jurídica (Livro I) - Parte 1 - DTB0341',
  'Ler O Capital à luz da forma jurídica (Livro II) - DTB0435',
  'Ler O Capital à luz da forma jurídica (Livro III) - DTB0456',
  'Liberdades Fundamentais - DES0314',
  'Licitações e Compras Governamentais - DES0340',
  'Lições Introdutórias de Direito Digital e Direito Internacional Privado - DIN0453',
  'Lógica e Metodologia Jurídica - DFD0217',
  'Mais um Direito Fundamental - DES0338',
  'Mediação e Conciliação Judiciais e Extrajudiciais - DPC0438',
  'Medicina Forense I - DPM0317',
  'Medicina Forense II - DPM0318',
  'Metodologia da Pesquisa Sócio-Jurídica - DFD0221',
  'Metodologia do Estudo do Direito - DFD0119',
  'Metodologia para Preparação de Monografia Jurídica - DFD0120',
  'Ministério Público - DES0527',
  'Mudanças climáticas e sua disciplina jurídica - DEF0462',
  'Negociação em Direito Empresarial - DCO0226',
  'New Theories of Law: Between Sociology, Economy, International Relations and Technology - DFD0128',
  'Noções de Contabilidade Empresarial - EAC0603',
  'Novas Tendências do Direito Processual - DPC0520',
  'O Direito do Trabalho e a Saúde das Trabalhadoras e Trabalhadores - DTB0543',
  'O Princípio da Legalidade no Direito Administrativo - DES0227',
  'Orçamento Público - DEF0326',
  'Organizações Internacionais - DIN0322',
  'Outro Direito Fundamental - DES0425',
  'Outro Direito Fundamental - Bis - DES0438',
  'Parcerias na Administração Pública - DES0528 / DES0541',
  'Planejamento Tributário - DEF0526',
  'Poder Público em Juízo - DPC0524',
  'Política criminal e processo penal - DPC0219',
  'Política Criminal da Pós-Modernidade - DPM0322',
  'Prática do Direito Internacional Público - DIN0320',
  'Precedentes Judiciais no Sistema de Justiça Civil - DPC0323',
  'Princípios Constitucionais do Direito Financeiro e Financiamento dos Direitos Fundamentais - DEF0330',
  'Princípios do Direito Administrativo - DES0335',
  'Privilégios, Garantias Reais e Patrimônio Separado - DCV0322',
  'Procedimentos Especiais no Âmbito Civil e Empresarial I - CPC - DPC0519',
  'Procedimentos Especiais no Âmbito Civil e Empresarial II: Legislação Extravagante - DPC0526',
  'Processo Administrativo - DES0445 / DES0446',
  'Processo civil e Tecnologia - II - DPC0448',
  'Processo Civil e Tecnologia I - DPC0451',
  'Processo Coletivo do Trabalho - DTB0452',
  'Processo e Esporte: Estudo dos Sistemas de Resolução de Disputas no Esporte - DPC0446',
  'Processo Penal e Crime: Justiça Restaurativa, Novos Métodos e Técnicas de Resolução não Adjudicada e Participação Comunitária - DPC0218',
  'Processo Penal e Tecnologia - DPC0444',
  'Propriedade Intelectual Aplicada: Função e Disfunção da Propriedade Intelectual em Estudos de Casos - DCO0222',
  'Propriedade Intelectual e Acesso ao Conhecimento - DCO0220',
  'Provas em Espécie - DPC0437',
  'Psicologia do Trabalho, Sociologia do Trabalho e Direito do Trabalho - DTB0444',
  'Psicopatologia Forense - DPM0419',
  'Quem é quem no Direito do Trabalho - DTB0337',
  'Questões Atuais de Direito Privado I: Fontes do Direito, Interpretação, Pessoa e Direitos da Personalidade, Negócio Jurídico, Cláusula Geral, Enriquecimento sem Causa, Justo Posto e Justo Natural, Liberdade e Justiça - DCV0521',
  'Questões Atuais de Direito Privado II: Obrigações, Contratos, Responsabilidade Civil, Direitos Reais, Propriedade Intelectual, Família e Sucessões - DCV0524',
  'Receitas Públicas e a Exploração de Petróleo, Minério e Energia Elétrica no Brasil - DEF0431',
  'Recursos em Espécie - DPC0430',
  'Relações Coletivas de Trabalho no Contexto da Globalização - DTB0442',
  'Relações Especiais de Trabalho - DTB0446',
  'Responsabilidade Civil do Estado - DES0535',
  'Responsabilidade Contratual - DCV0319',
  'Saúde e Segurança do Trabalho - DTB0535',
  'Segurança Pública e Preservação dos Direitos Fundamentais - DPM0320',
  'Seguridade Social - DTB0436',
  'Sistemas Alternativos de Solução dos Conflitos Trabalhistas I - Aspectos Teóricos e Conceitos Fundamentais - DTB0431',
  'Sistemas Alternativos de Solução dos Conflitos Trabalhistas II - Oficinas de Exercício por Simulação e Casuística - DTB0440',
  'Sistemas Políticos e Eleitorais - DES0526',
  'Sociologia da Constituição - DFD0130',
  'Sociologia Jurídica - DFD0215',
  'Sociology of Criminal Law, Sustainability and Technology - DFD0134',
  'Solução de Conflitos entre Empresas - DCO0324',
  'Solução de Disputas - Princípios Gerais - DIN0440',
  'Sucessão Testamentária - DCV0430',
  'Técnicas de Solução de Litígio com a Administração Pública - DPC0443',
  'Temas Avançados de Direito do Comércio Internacional e Arbitragem - DIN0540',
  'Temas de Criminologia Clínica - DPM0422',
  'Temas Essenciais à Natureza Humana e seus Impactos Penais - DPM0423',
  'Temas Fundamentais de Direito da Execução Penal - DPM0425',
  'Temas Fundamentais do Direito Penal I - DPM0521',
  'Temas Fundamentais do Direito Penal II - DPM0528',
  'Tendências do Direito da Empresa em Crise - DCO0508',
  'Teoria Crítico Estruturalista do Direito Comercial - Visões Tradicionais e Alternativas dos Institutos - DCO0322',
  'Teoria da Tributação: Aspectos Econômicos - DEF0212',
  'Teoria do Estado Brasileiro I - DES0124',
  'Teoria do Estado Brasileiro II - DES0225',
  'Teoria Geral da Arbitragem - DPC0447',
  'Teoria Geral das Despesas Públicas - DEF0332',
  'Teoria Geral das Obrigações - DCV0215',
  'Teoria Geral das Receitas Públicas - DEF0214',
  'Teoria Geral do Direito do Trabalho I - DTB0525',
  'Teoria Geral do Direito do Trabalho II - DTB0526',
  'Teoria Geral do Direito Penal I - DPM0215',
  'Teoria Geral do Direito Penal II - DPM0216',
  'Teoria Geral do Direito Privado I - DCV0125',
  'Teoria Geral do Direito Privado II - DCV0126',
  'Teoria Geral do Estado I - DES0125',
  'Teoria Geral do Estado II - DES0126',
  'Teoria Geral do Processo - DPC0215',
  'Teoria Geral dos Contratos e Contratos do Código Civil - DCV0216',
  'Teorias Críticas do Direito - DFD0420',
  'Terceiro Setor e o Direito Administrativo - DES0530 / DES0539',
  'Testes de legalidade: métodos para o controle da discricionariedade administrativa - DES0453',
  'Tipo Contratual no Direito Privado Contemporâneo - DCV0323',
  'Tópicos Avançados de Direito Ambiental I - DEF0433',
  'Tópicos Contemporâneos de Direito Civil Aplicado I - DCV0517',
  'Tópicos Contemporâneos de Direito Civil Aplicado II - DCV0520',
  'Trabalho de Conclusão de Curso I - 0200115',
  'Trabalho de Conclusão de Curso II - 0200116',
  'Transparência Administrativa e Comunicação de Interesse Geral - DES0348',
  'Tributação da Economia Digital - DEF0334',
  'Tributação Direta das Pessoas Jurídicas - DEF0537',
  'Tributação Francesa e Internacional - 0200110',
  'Tributos Estaduais e Municipais - DEF0540',
  'Tributos Federais - DEF0533',
  'Tutela Jurisdicional dos Interesses Transindividuais - DPC0525',
  'Tutela Processual dos Direitos Humanos nas Relações de Trabalho - DTB0339',
  'Tutela Processual dos Direitos Humanos nas Relações de Trabalho I - DTB0329',
  'Tutela Processual dos Direitos Humanos nas Relações de Trabalho II - DTB0336',
  'Tutelas Sumárias em Espécie - DPC0523',
  'Um Direito Fundamental - DES0329',
  'Visão Crítica do Direito do Trabalho na Sociedade Capitalista - DTB0527',
];
