export const pdfQuestions3 = [
  {
    subject: "Direito Administrativo",
    topic: "Princípios da Administração Pública",
    statement: "O princípio que impõe à Administração Pública o dever de agir com transparência, permitindo o controle social de seus atos, é o princípio da:",
    options: ["Legalidade", "Impessoalidade", "Moralidade", "Publicidade", "Eficiência"],
    correct_answer: 3,
    explanation: "Gabarito: D. O princípio da publicidade exige a divulgação dos atos administrativos para conhecimento público e controle.",
    difficulty: "facil",
    exam_board: "FGV",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Poderes Administrativos",
    statement: "O poder que permite à Administração Pública distribuir e escalonar as funções de seus órgãos, estabelecendo a relação de subordinação entre os agentes, é o poder:",
    options: ["Disciplinar", "Hierárquico", "Regulamentar", "De Polícia", "Discricionário"],
    correct_answer: 1,
    explanation: "Gabarito: B. O poder hierárquico é o que organiza a estrutura interna da administração.",
    difficulty: "facil",
    exam_board: "FCC",
    year: 2023
  },
  {
    subject: "Direito Administrativo",
    topic: "Atos Administrativos",
    statement: "Qual dos elementos abaixo é considerado vinculado em todo e qualquer ato administrativo, inclusive nos discricionários?",
    options: ["Motivo", "Objeto", "Finalidade", "Conveniência", "Oportunidade"],
    correct_answer: 2,
    explanation: "Gabarito: C. Competência, finalidade e forma são sempre elementos vinculados.",
    difficulty: "media",
    exam_board: "VUNESP",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Agentes Públicos",
    statement: "Os agentes que exercem funções de alta gestão, com vínculo político e cujas competências derivam diretamente da Constituição, são classificados como:",
    options: ["Servidores Públicos", "Empregados Públicos", "Agentes Políticos", "Agentes Honoríficos", "Agentes Delegados"],
    correct_answer: 2,
    explanation: "Gabarito: C. Agentes políticos são os ocupantes dos cargos do primeiro escalão do governo.",
    difficulty: "media",
    exam_board: "CESPE/CEBRASPE",
    year: 2023
  },
  {
    subject: "Direito Administrativo",
    topic: "Licitações e Contratos",
    statement: "De acordo com a Lei 14.133/2021, a modalidade de licitação para escolha de trabalho técnico, científico ou artístico, mediante a instituição de prêmios ou remuneração aos vencedores, é o:",
    options: ["Pregão", "Concorrência", "Concurso", "Leilão", "Diálogo Competitivo"],
    correct_answer: 2,
    explanation: "Gabarito: C. O concurso é a modalidade para trabalhos técnicos, científicos ou artísticos.",
    difficulty: "facil",
    exam_board: "FGV",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Responsabilidade Civil do Estado",
    statement: "A teoria que fundamenta a responsabilidade objetiva do Estado no Brasil, exigindo apenas o nexo causal entre a conduta administrativa e o dano, é a teoria do:",
    options: ["Risco Administrativo", "Risco Integral", "Culpa do Serviço", "Irresponsabilidade", "Culpa Anônima"],
    correct_answer: 0,
    explanation: "Gabarito: A. A regra geral no Brasil é a responsabilidade objetiva baseada no risco administrativo.",
    difficulty: "media",
    exam_board: "VUNESP",
    year: 2023
  },
  {
    subject: "Direito Administrativo",
    topic: "Organização Administrativa",
    statement: "As autarquias são entidades que integram a Administração Pública:",
    options: ["Direta", "Indireta", "Centralizada", "Fundacional", "Paraestatal"],
    correct_answer: 1,
    explanation: "Gabarito: B. Autarquias, fundações públicas, empresas públicas e sociedades de economia mista compõem a administração indireta.",
    difficulty: "facil",
    exam_board: "FCC",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Poder de Polícia",
    statement: "Um dos atributos do poder de polícia que permite à Administração Pública executar suas decisões diretamente, inclusive com o uso da força, sem necessidade de autorização judicial prévia, é a:",
    options: ["Discricionariedade", "Autoexecutoriedade", "Coercibilidade", "Legalidade", "Tipicidade"],
    correct_answer: 1,
    explanation: "Gabarito: B. A autoexecutoriedade permite a execução direta do ato pela administração.",
    difficulty: "media",
    exam_board: "CESPE/CEBRASPE",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Serviços Públicos",
    statement: "A concessão de serviço público é a delegação de sua prestação, feita pelo poder concedente, mediante licitação, na modalidade:",
    options: ["Pregão", "Concorrência ou Diálogo Competitivo", "Leilão", "Concurso", "Convite"],
    correct_answer: 1,
    explanation: "Gabarito: B. Conforme a Lei 14.133/21 e Lei 8.987/95, concessões exigem concorrência ou diálogo competitivo.",
    difficulty: "media",
    exam_board: "FGV",
    year: 2023
  },
  {
    subject: "Direito Administrativo",
    topic: "Improbidade Administrativa",
    statement: "De acordo com a Lei 8.429/92 (com alterações da Lei 14.230/21), para a configuração de ato de improbidade administrativa é necessária a presença de:",
    options: ["Culpa leve", "Culpa grave", "Dolo específico", "Dolo genérico", "Apenas o dano"],
    correct_answer: 2,
    explanation: "Gabarito: C. A nova lei exige o dolo específico para todos os atos de improbidade.",
    difficulty: "dificil",
    exam_board: "VUNESP",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Processo Administrativo",
    statement: "Na Lei 9.784/99, o princípio que veda a aplicação retroativa de nova interpretação de norma administrativa é o princípio da:",
    options: ["Legalidade", "Segurança Jurídica", "Eficiência", "Moralidade", "Motivação"],
    correct_answer: 1,
    explanation: "Gabarito: B. A vedação à retroatividade de nova interpretação visa garantir a segurança jurídica.",
    difficulty: "media",
    exam_board: "FCC",
    year: 2023
  },
  {
    subject: "Direito Administrativo",
    topic: "Bens Públicos",
    statement: "Os bens públicos que se destinam ao uso da própria administração, como edifícios de repartições públicas, são classificados como bens de:",
    options: ["Uso comum do povo", "Uso especial", "Dominicais", "Uso coletivo", "Uso privado"],
    correct_answer: 1,
    explanation: "Gabarito: B. Bens de uso especial são os destinados a serviço ou estabelecimento da administração.",
    difficulty: "facil",
    exam_board: "CESPE/CEBRASPE",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Controle da Administração",
    statement: "O controle exercido pelo Poder Judiciário sobre os atos da Administração Pública limita-se ao exame da:",
    options: ["Conveniência", "Oportunidade", "Legalidade", "Mérito", "Eficiência política"],
    correct_answer: 2,
    explanation: "Gabarito: C. O Judiciário não pode invadir o mérito administrativo (conveniência e oportunidade).",
    difficulty: "media",
    exam_board: "FGV",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Princípios",
    statement: "O princípio da eficiência foi introduzido expressamente no caput do art. 37 da Constituição Federal pela Emenda Constitucional nº:",
    options: ["19/1998", "20/1998", "45/2004", "103/2019", "1/1992"],
    correct_answer: 0,
    explanation: "Gabarito: A. A EC 19/98 incluiu a eficiência como princípio constitucional explícito.",
    difficulty: "facil",
    exam_board: "VUNESP",
    year: 2023
  },
  {
    subject: "Direito Administrativo",
    topic: "Atos Administrativos",
    statement: "A extinção de um ato administrativo válido por razões de conveniência e oportunidade é denominada:",
    options: ["Anulação", "Revogação", "Cassação", "Caducidade", "Contraposição"],
    correct_answer: 1,
    explanation: "Gabarito: B. A revogação retira do mundo jurídico um ato válido por mérito administrativo.",
    difficulty: "facil",
    exam_board: "FCC",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Poderes",
    statement: "O poder de polícia é indelegável a pessoas jurídicas de direito privado, exceto quanto aos atos meramente preparatórios ou executórios, segundo entendimento do STF.",
    options: ["Certo", "Errado"],
    correct_answer: 0,
    explanation: "Gabarito: Certo. O STF fixou tese permitindo a delegação das fases de consentimento e fiscalização a empresas estatais.",
    difficulty: "dificil",
    exam_board: "CESPE/CEBRASPE",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Organização Administrativa",
    statement: "As sociedades de economia mista devem ser criadas sob a forma de:",
    options: ["Sociedade Limitada", "Sociedade Anônima", "Cooperativa", "Fundação", "Associação"],
    correct_answer: 1,
    explanation: "Gabarito: B. Por lei, as sociedades de economia mista devem ser S/A.",
    difficulty: "media",
    exam_board: "FGV",
    year: 2023
  },
  {
    subject: "Direito Administrativo",
    topic: "Agentes Públicos",
    statement: "A demissão de servidor público estável só pode ocorrer mediante sentença judicial transitada em julgado, processo administrativo com ampla defesa ou procedimento de avaliação periódica de desempenho.",
    options: ["Certo", "Errado"],
    correct_answer: 0,
    explanation: "Gabarito: Certo. São as hipóteses previstas no art. 41 da CF.",
    difficulty: "media",
    exam_board: "VUNESP",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Licitações",
    statement: "Na nova Lei de Licitações (14.133/21), o critério de julgamento 'maior desconto' é aplicável quando o edital prevê:",
    options: ["Menor preço", "Melhor técnica", "Técnica e preço", "Maior retorno econômico", "Preço fixado em tabela"],
    correct_answer: 4,
    explanation: "Gabarito: E. O maior desconto incide sobre preços fixados em tabelas oficiais.",
    difficulty: "media",
    exam_board: "FCC",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Responsabilidade Civil",
    statement: "Em caso de danos causados por multidões ou atos de terceiros, a responsabilidade do Estado é, em regra:",
    options: ["Objetiva", "Subjetiva (por omissão)", "Inexistente", "Integral", "Solidária"],
    correct_answer: 1,
    explanation: "Gabarito: B. Em omissões genéricas, a responsabilidade é subjetiva (falta do serviço).",
    difficulty: "dificil",
    exam_board: "CESPE/CEBRASPE",
    year: 2023
  },
  {
    subject: "Direito Administrativo",
    topic: "Bens Públicos",
    statement: "A usucapião de bens públicos é permitida no Brasil caso o bem esteja desafetado há mais de 20 anos.",
    options: ["Certo", "Errado"],
    correct_answer: 1,
    explanation: "Gabarito: Errado. Bens públicos são imprescritíveis (não sujeitos a usucapião).",
    difficulty: "facil",
    exam_board: "FGV",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Contratos Administrativos",
    statement: "A cláusula que permite à Administração alterar unilateralmente o contrato para melhor adequação às finalidades de interesse público é uma:",
    options: ["Cláusula Pétrea", "Cláusula Exorbitante", "Cláusula de Barreira", "Cláusula Resolutiva", "Cláusula de Reajuste"],
    correct_answer: 1,
    explanation: "Gabarito: B. As cláusulas exorbitantes colocam a administração em posição de supremacia.",
    difficulty: "facil",
    exam_board: "VUNESP",
    year: 2023
  },
  {
    subject: "Direito Administrativo",
    topic: "Serviços Públicos",
    statement: "O princípio que exige que o serviço público seja prestado de forma contínua, sem interrupções injustificadas, é o princípio da:",
    options: ["Modicidade das tarifas", "Continuidade", "Generalidade", "Cortesia", "Atualidade"],
    correct_answer: 1,
    explanation: "Gabarito: B. A continuidade é essencial para serviços públicos.",
    difficulty: "facil",
    exam_board: "FCC",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Improbidade",
    statement: "A sanção de suspensão dos direitos políticos por ato de improbidade que gera enriquecimento ilícito pode chegar a:",
    options: ["5 anos", "8 anos", "10 anos", "14 anos", "20 anos"],
    correct_answer: 3,
    explanation: "Gabarito: D. A Lei 14.230/21 fixou o prazo de até 14 anos para enriquecimento ilícito.",
    difficulty: "dificil",
    exam_board: "CESPE/CEBRASPE",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Processo Administrativo",
    statement: "No processo administrativo federal, o prazo para interposição de recurso administrativo é de:",
    options: ["5 dias", "10 dias", "15 dias", "30 dias", "45 dias"],
    correct_answer: 1,
    explanation: "Gabarito: B. Conforme a Lei 9.784/99, o prazo é de 10 dias.",
    difficulty: "media",
    exam_board: "FGV",
    year: 2023
  },
  {
    subject: "Direito Administrativo",
    topic: "Atos Administrativos",
    statement: "O atributo do ato administrativo que impõe a obrigação de seu cumprimento pelos administrados, independentemente de sua concordância, é a:",
    options: ["Presunção de Legitimidade", "Imperatividade", "Autoexecutoriedade", "Tipicidade", "Exigibilidade"],
    correct_answer: 1,
    explanation: "Gabarito: B. A imperatividade é o poder de impor obrigações unilateralmente.",
    difficulty: "media",
    exam_board: "VUNESP",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Organização Administrativa",
    statement: "A transferência de execução de serviço público de uma pessoa jurídica para outra, por meio de lei, denomina-se:",
    options: ["Desconcentração", "Descentralização por serviços", "Descentralização por colaboração", "Avocação", "Delegação"],
    correct_answer: 1,
    explanation: "Gabarito: B. A descentralização por serviços (outorga) ocorre via lei para entidades da administração indireta.",
    difficulty: "media",
    exam_board: "FCC",
    year: 2023
  },
  {
    subject: "Direito Administrativo",
    topic: "Poder de Polícia",
    statement: "A taxa de polícia é uma espécie tributária que tem como fato gerador o exercício regular do poder de polícia.",
    options: ["Certo", "Errado"],
    correct_answer: 0,
    explanation: "Gabarito: Certo. É a previsão do Código Tributário Nacional e da CF.",
    difficulty: "facil",
    exam_board: "CESPE/CEBRASPE",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Agentes Públicos",
    statement: "A acumulação remunerada de dois cargos de professor é permitida pela Constituição, desde que haja compatibilidade de horários.",
    options: ["Certo", "Errado"],
    correct_answer: 0,
    explanation: "Gabarito: Certo. É uma das exceções à regra de não acumulação.",
    difficulty: "facil",
    exam_board: "FGV",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Licitações",
    statement: "O 'diálogo competitivo' é uma modalidade de licitação restrita a contratações que envolvam inovação tecnológica ou técnica.",
    options: ["Certo", "Errado"],
    correct_answer: 0,
    explanation: "Gabarito: Certo. É voltado para soluções complexas que a administração não consegue definir sozinha.",
    difficulty: "media",
    exam_board: "VUNESP",
    year: 2023
  }
];
