export const pdfQuestions4 = [
  {
    subject: "Direito Administrativo",
    topic: "Atos Administrativos",
    statement: "A 'presunção de legitimidade' dos atos administrativos significa que:",
    options: [
      "O ato é perfeito e não pode ser anulado.",
      "O ato presume-se verdadeiro e conforme a lei até prova em contrário.",
      "O particular deve provar que o ato é legal para que ele tenha validade.",
      "O Judiciário não pode analisar a validade do ato.",
      "O ato só produz efeitos após confirmação pelo Tribunal de Contas."
    ],
    correct_answer: 1,
    explanation: "Gabarito: B. A presunção é juris tantum (relativa), admitindo prova em contrário.",
    difficulty: "facil",
    exam_board: "FGV",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Poderes Administrativos",
    statement: "O poder que a Administração possui para punir infrações funcionais de seus servidores é o poder:",
    options: ["Hierárquico", "Disciplinar", "De Polícia", "Regulamentar", "Vinculado"],
    correct_answer: 1,
    explanation: "Gabarito: B. O poder disciplinar é voltado para a punição de quem possui vínculo interno com a administração.",
    difficulty: "facil",
    exam_board: "FCC",
    year: 2023
  },
  {
    subject: "Direito Administrativo",
    topic: "Organização Administrativa",
    statement: "A criação de uma secretaria dentro de um ministério é um exemplo de:",
    options: ["Descentralização", "Desconcentração", "Privatização", "Terceirização", "Outorga"],
    correct_answer: 1,
    explanation: "Gabarito: B. Desconcentração é a distribuição interna de competências dentro de uma mesma pessoa jurídica.",
    difficulty: "media",
    exam_board: "VUNESP",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Responsabilidade Civil",
    statement: "O Estado responde objetivamente pelos danos que seus agentes, nessa qualidade, causarem a terceiros, assegurado o direito de regresso contra o responsável em caso de dolo ou culpa.",
    options: ["Certo", "Errado"],
    correct_answer: 0,
    explanation: "Gabarito: Certo. É a redação do art. 37, §6º da CF.",
    difficulty: "facil",
    exam_board: "CESPE/CEBRASPE",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Licitações",
    statement: "Na Lei 14.133/21, a fase de lances no pregão é, em regra:",
    options: ["Presencial", "Eletrônica", "Por carta fechada", "Oral e obrigatória", "Sigilosa"],
    correct_answer: 1,
    explanation: "Gabarito: B. A nova lei prioriza o formato eletrônico para as licitações.",
    difficulty: "facil",
    exam_board: "FGV",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Agentes Públicos",
    statement: "O teto remuneratório constitucional aplica-se às empresas públicas e sociedades de economia mista que recebam recursos da União para pagamento de despesas de pessoal ou de custeio em geral.",
    options: ["Certo", "Errado"],
    correct_answer: 0,
    explanation: "Gabarito: Certo. Se a estatal for dependente do tesouro, o teto se aplica.",
    difficulty: "media",
    exam_board: "VUNESP",
    year: 2023
  },
  {
    subject: "Direito Administrativo",
    topic: "Controle da Administração",
    statement: "O controle externo do Poder Executivo será exercido pelo Congresso Nacional, com o auxílio do:",
    options: ["Ministério Público", "Tribunal de Contas da União", "Poder Judiciário", "Conselho da República", "Advocacia-Geral da União"],
    correct_answer: 1,
    explanation: "Gabarito: B. O TCU é o órgão técnico que auxilia o Legislativo no controle externo.",
    difficulty: "facil",
    exam_board: "FCC",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Bens Públicos",
    statement: "Bens dominicais são aqueles que, embora pertencentes ao Estado, não possuem uma destinação pública específica, podendo ser alienados observadas as exigências legais.",
    options: ["Certo", "Errado"],
    correct_answer: 0,
    explanation: "Gabarito: Certo. São bens do patrimônio disponível do Estado.",
    difficulty: "media",
    exam_board: "CESPE/CEBRASPE",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Serviços Públicos",
    statement: "A encampação é a retomada do serviço pelo poder concedente durante o prazo da concessão, por motivo de interesse público, mediante lei autorizativa específica e após prévio pagamento de indenização.",
    options: ["Certo", "Errado"],
    correct_answer: 0,
    explanation: "Gabarito: Certo. É uma das formas de extinção da concessão.",
    difficulty: "dificil",
    exam_board: "FGV",
    year: 2023
  },
  {
    subject: "Direito Administrativo",
    topic: "Improbidade",
    statement: "A perda da função pública por ato de improbidade administrativa atinge apenas o vínculo que o agente mantinha com o poder público no momento da prática do ato.",
    options: ["Certo", "Errado"],
    correct_answer: 1,
    explanation: "Gabarito: Errado. A Lei 14.230/21 prevê que atinge o vínculo atual, mas o juiz pode estender a outros vínculos em casos excepcionais.",
    difficulty: "dificil",
    exam_board: "VUNESP",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Processo Administrativo",
    statement: "No processo administrativo, a Administração tem o dever de motivar seus atos, indicando os fatos e os fundamentos jurídicos, especialmente quando neguem direitos ou imponham deveres.",
    options: ["Certo", "Errado"],
    correct_answer: 0,
    explanation: "Gabarito: Certo. A motivação é essencial para o controle da legalidade.",
    difficulty: "facil",
    exam_board: "FCC",
    year: 2023
  },
  {
    subject: "Direito Administrativo",
    topic: "Atos Administrativos",
    statement: "A convalidação é o ato pelo qual a Administração supre vícios sanáveis de um ato administrativo, com efeitos retroativos (ex tunc).",
    options: ["Certo", "Errado"],
    correct_answer: 0,
    explanation: "Gabarito: Certo. Só é possível se não houver lesão ao interesse público nem prejuízo a terceiros.",
    difficulty: "media",
    exam_board: "CESPE/CEBRASPE",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Poder de Polícia",
    statement: "O ciclo do poder de polícia compreende as fases de ordem, consentimento, fiscalização e sanção.",
    options: ["Certo", "Errado"],
    correct_answer: 0,
    explanation: "Gabarito: Certo. É a divisão doutrinária clássica do poder de polícia.",
    difficulty: "media",
    exam_board: "FGV",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Organização Administrativa",
    statement: "As fundações públicas de direito privado são criadas por lei específica, enquanto as de direito público têm sua criação autorizada por lei.",
    options: ["Certo", "Errado"],
    correct_answer: 1,
    explanation: "Gabarito: Errado. É o contrário: as de direito público são criadas por lei (como autarquias), as de direito privado têm criação autorizada.",
    difficulty: "dificil",
    exam_board: "VUNESP",
    year: 2023
  },
  {
    subject: "Direito Administrativo",
    topic: "Princípios",
    statement: "O princípio da moralidade administrativa exige que o agente público atue não apenas conforme a lei, mas também conforme padrões éticos de probidade e boa-fé.",
    options: ["Certo", "Errado"],
    correct_answer: 0,
    explanation: "Gabarito: Certo. A moralidade jurídica difere da moralidade comum.",
    difficulty: "facil",
    exam_board: "FCC",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Licitações",
    statement: "A 'inviabilidade de competição' é o fundamento para a:",
    options: ["Dispensa de licitação", "Inexigibilidade de licitação", "Licitação deserta", "Licitação fracassada", "Licitação carona"],
    correct_answer: 1,
    explanation: "Gabarito: B. Se não há competição possível, a licitação é inexigível.",
    difficulty: "facil",
    exam_board: "CESPE/CEBRASPE",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Responsabilidade Civil",
    statement: "A responsabilidade do Estado por atos jurisdicionais (decisões judiciais) é a regra no ordenamento brasileiro.",
    options: ["Certo", "Errado"],
    correct_answer: 1,
    explanation: "Gabarito: Errado. A regra é a irresponsabilidade por atos judiciais, salvo erro judiciário ou prisão além do tempo.",
    difficulty: "media",
    exam_board: "FGV",
    year: 2023
  },
  {
    subject: "Direito Administrativo",
    topic: "Agentes Públicos",
    statement: "O estágio probatório para servidores públicos estatutários tem duração de:",
    options: ["1 ano", "2 anos", "3 anos", "5 anos", "Estágio não tem prazo fixo"],
    correct_answer: 2,
    explanation: "Gabarito: C. Após a EC 19/98, o prazo de estabilidade e estágio probatório é de 3 anos.",
    difficulty: "facil",
    exam_board: "VUNESP",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Contratos Administrativos",
    statement: "A 'exceção do contrato não cumprido' (exceptio non adimpleti contractus) pode ser invocada pelo particular contra a Administração imediatamente após o primeiro atraso de pagamento.",
    options: ["Certo", "Errado"],
    correct_answer: 1,
    explanation: "Gabarito: Errado. O particular deve aguardar o prazo legal (geralmente 2 meses na nova lei) antes de suspender a execução.",
    difficulty: "dificil",
    exam_board: "FCC",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Bens Públicos",
    statement: "A afetação de um bem público significa dar a ele uma destinação pública específica.",
    options: ["Certo", "Errado"],
    correct_answer: 0,
    explanation: "Gabarito: Certo. Desafetação é o inverso (retirar a destinação).",
    difficulty: "facil",
    exam_board: "CESPE/CEBRASPE",
    year: 2023
  },
  {
    subject: "Direito Administrativo",
    topic: "Serviços Públicos",
    statement: "A tarifa ou preço público é a contraprestação paga pelo usuário nos serviços públicos delegados (concessão/permissão).",
    options: ["Certo", "Errado"],
    correct_answer: 0,
    explanation: "Gabarito: Certo. Diferencia-se da taxa, que tem natureza tributária.",
    difficulty: "media",
    exam_board: "FGV",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Improbidade",
    statement: "A ação de improbidade administrativa tem natureza cível-administrativa, não possuindo caráter penal.",
    options: ["Certo", "Errado"],
    correct_answer: 0,
    explanation: "Gabarito: Certo. Embora as sanções sejam graves, a natureza não é penal.",
    difficulty: "media",
    exam_board: "VUNESP",
    year: 2023
  },
  {
    subject: "Direito Administrativo",
    topic: "Processo Administrativo",
    statement: "O direito da Administração de anular os atos administrativos de que decorram efeitos favoráveis para os destinatários decai em:",
    options: ["2 anos", "5 anos", "10 anos", "Não decai", "20 anos"],
    correct_answer: 1,
    explanation: "Gabarito: B. O prazo decadencial é de 5 anos, salvo comprovada má-fé.",
    difficulty: "media",
    exam_board: "FCC",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Atos Administrativos",
    statement: "O ato administrativo que apresenta vício de competência quanto à pessoa (ex: agente incompetente) é sempre nulo e jamais pode ser convalidado.",
    options: ["Certo", "Errado"],
    correct_answer: 1,
    explanation: "Gabarito: Errado. Se a competência não for exclusiva, o ato pode ser convalidado por ratificação.",
    difficulty: "dificil",
    exam_board: "CESPE/CEBRASPE",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Poderes",
    statement: "O poder regulamentar é a prerrogativa do Chefe do Executivo de editar atos normativos para fiel execução das leis.",
    options: ["Certo", "Errado"],
    correct_answer: 0,
    explanation: "Gabarito: Certo. É um poder derivado ou secundário.",
    difficulty: "facil",
    exam_board: "FGV",
    year: 2023
  },
  {
    subject: "Direito Administrativo",
    topic: "Organização Administrativa",
    statement: "As empresas públicas podem ser constituídas sob qualquer forma jurídica admitida em direito.",
    options: ["Certo", "Errado"],
    correct_answer: 0,
    explanation: "Gabarito: Certo. Diferente das S.E.M., as empresas públicas não são restritas à forma de S/A.",
    difficulty: "media",
    exam_board: "VUNESP",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Princípios",
    statement: "O princípio da autotutela permite que a Administração anule seus próprios atos quando eivados de vícios de legalidade.",
    options: ["Certo", "Errado"],
    correct_answer: 0,
    explanation: "Gabarito: Certo. Súmula 473 do STF.",
    difficulty: "facil",
    exam_board: "FCC",
    year: 2023
  },
  {
    subject: "Direito Administrativo",
    topic: "Licitações",
    statement: "O leilão é a modalidade de licitação para a venda de bens móveis inservíveis ou de bens imóveis cuja aquisição haja derivado de procedimentos judiciais ou de dação em pagamento.",
    options: ["Certo", "Errado"],
    correct_answer: 0,
    explanation: "Gabarito: Certo. Definição clássica mantida na nova lei.",
    difficulty: "media",
    exam_board: "CESPE/CEBRASPE",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Agentes Públicos",
    statement: "O servidor público ocupante de cargo em comissão pode ser exonerado a qualquer tempo, sem necessidade de motivação ou processo administrativo.",
    options: ["Certo", "Errado"],
    correct_answer: 0,
    explanation: "Gabarito: Certo. São cargos de livre nomeação e exoneração (ad nutum).",
    difficulty: "facil",
    exam_board: "FGV",
    year: 2024
  },
  {
    subject: "Direito Administrativo",
    topic: "Responsabilidade Civil",
    statement: "A responsabilidade objetiva do Estado aplica-se também às pessoas jurídicas de direito privado prestadoras de serviços públicos, em relação a terceiros usuários e não usuários do serviço.",
    options: ["Certo", "Errado"],
    correct_answer: 0,
    explanation: "Gabarito: Certo. Entendimento consolidado pelo STF (RE 591.874).",
    difficulty: "media",
    exam_board: "VUNESP",
    year: 2023
  }
];
