-- Opcional: incluir 'fixed_gaps' na constraint CHECK de srs_algorithm, se existir no seu projeto.
-- Exemplo (ajuste o nome da constraint após: select conname from pg_constraint where conrelid = 'public.spaced_topics'::regclass):
--
-- alter table public.spaced_topics drop constraint if exists spaced_topics_srs_algorithm_check;
-- alter table public.spaced_topics
--   add constraint spaced_topics_srs_algorithm_check
--   check (srs_algorithm is null or srs_algorithm in ('fixed', 'fixed_gaps', 'sm2', 'fsrs'));
